import type { Category, Product, Seller, OrderRequest } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Toys',
    slug: 'toys',
    code_prefix: 'TOY',
    description: 'Handpicked toys for all ages — local shops and trusted makers',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    slug: 'fashion',
    code_prefix: 'FASH',
    description: 'Clothing, handloom fabrics, and wearables from Kerala designers',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Electronics',
    slug: 'electronics',
    code_prefix: 'ELEC',
    description: 'Gadgets, accessories, and tech products',
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Home',
    slug: 'home',
    code_prefix: 'HOME',
    description: 'Home décor, ceramic crafts, and household essentials',
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Gifts',
    slug: 'gifts',
    code_prefix: 'GIFT',
    description: 'Curated gift hampers and special celebration boxes',
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    name: 'Accessories',
    slug: 'accessories',
    code_prefix: 'ACC',
    description: 'Personal accessories, handcrafted keychains, and jewellery',
    display_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-7',
    name: '3D Products',
    slug: '3d-products',
    code_prefix: '3DP',
    description: 'Custom 3D-printed nameplates and figures from local studios',
    display_order: 7,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-8',
    name: 'Others',
    slug: 'others',
    code_prefix: 'OTH',
    description: 'Unique finds and specialty goods from across Kerala',
    display_order: 8,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SELLERS: Seller[] = [
  {
    id: 'sel-1',
    business_name: 'Thrissur Handcrafts & Toys',
    contact_person: 'Suresh Menon',
    phone: '9400634966',
    whatsapp: '9400634966',
    location: 'Thrissur, Kerala',
    notes: 'Local toy wholesale and artisan collective.',
    status: 'active',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sel-2',
    business_name: 'Kerala 3D Labs',
    contact_person: 'Arjun V.',
    phone: '9400634966',
    whatsapp: '9400634966',
    location: 'Kochi, Kerala',
    notes: '3D printing workshop with 4-day delivery turnaround.',
    status: 'verified',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Remote Control Toy Car',
    code: 'EK-TOY-001',
    slug: 'ek-toy-001',
    category_id: 'cat-1',
    seller_id: 'sel-1',
    description: 'High-speed remote control toy car with rechargeable battery and 2.4GHz remote controller. Suitable for ages 6 and above. Built for indoor and outdoor racing.',
    price: 750,
    price_display_mode: 'exact',
    availability: 'available',
    location: 'Thrissur, Kerala',
    show_seller: false,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[0],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-2',
    name: 'Building Blocks Creative Set (100 Pcs)',
    code: 'EK-TOY-002',
    slug: 'ek-toy-002',
    category_id: 'cat-1',
    seller_id: 'sel-1',
    description: 'Classic multi-colour building blocks set. 100 interlocking pieces that develop spatial awareness, creativity, and fine motor skills in young children.',
    price: 550,
    price_display_mode: 'exact',
    availability: 'available',
    location: 'Thrissur, Kerala',
    show_seller: false,
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[0],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-3',
    name: 'Handloom Kasavu Cotton Saree',
    code: 'EK-FASH-001',
    slug: 'ek-fash-001',
    category_id: 'cat-2',
    seller_id: 'sel-1',
    description: 'Authentic Kerala handloom cotton saree with traditional golden kasavu border. Woven by master weavers in Thrissur. Lightweight and elegant for celebrations.',
    price: 1800,
    price_display_mode: 'approximate',
    availability: 'check_availability',
    location: 'Kuthampully, Thrissur',
    show_seller: true,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[1],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-4',
    name: 'Pure Cotton Men\'s Kurta',
    code: 'EK-FASH-002',
    slug: 'ek-fash-002',
    category_id: 'cat-2',
    seller_id: 'sel-1',
    description: 'Breathable, lightweight 100% cotton casual kurta. Minimalistic styling with mandarin collar. Available in off-white, light blue, and beige.',
    price: 650,
    price_display_mode: 'exact',
    availability: 'available',
    location: 'Ernakulam, Kerala',
    show_seller: false,
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[1],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-5',
    name: '7-in-1 Aluminium USB-C Hub',
    code: 'EK-ELEC-001',
    slug: 'ek-elec-001',
    category_id: 'cat-3',
    seller_id: 'sel-1',
    description: 'Premium aluminium 7-in-1 USB-C Hub with 4K HDMI, 3x USB 3.0 ports, SD/TF dual card readers, and 100W Power Delivery pass-through charging.',
    price: 1200,
    price_display_mode: 'exact',
    availability: 'available',
    location: 'Kochi, Kerala',
    show_seller: false,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[2],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-6',
    name: 'Handcrafted Ceramic Coffee Mug',
    code: 'EK-HOME-001',
    slug: 'ek-home-001',
    category_id: 'cat-4',
    seller_id: 'sel-1',
    description: 'Artisan hand-thrown stoneware mug (350ml). Matte stone finish with glazed interior. Microwave and dishwasher safe. Each piece has distinct texture variations.',
    price: 380,
    price_display_mode: 'exact',
    availability: 'available',
    location: 'Thrissur, Kerala',
    show_seller: false,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[3],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-7',
    name: 'Curated Artisan Gift Hamper',
    code: 'EK-GIFT-001',
    slug: 'ek-gift-001',
    category_id: 'cat-5',
    seller_id: 'sel-1',
    description: 'Custom curated festive hamper containing Kerala spices, handmade scented candle, cocoa chocolates, and a handwritten calligraphed note card.',
    price: 1500,
    price_display_mode: 'on_request',
    availability: 'check_availability',
    location: 'Kozhikode, Kerala',
    show_seller: false,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[4],
    sellers: INITIAL_SELLERS[0],
    product_images: [],
  },
  {
    id: 'prod-8',
    name: 'Custom 3D-Printed Nameplate',
    code: 'EK-3DP-001',
    slug: 'ek-3dp-001',
    category_id: 'cat-7',
    seller_id: 'sel-2',
    description: 'Personalised dual-tone 3D printed nameplate for house doors, desks, or offices. Weather-resistant PETG material. Customized with any name or Malayalam script.',
    price: 600,
    price_display_mode: 'approximate',
    availability: 'available',
    location: 'Kochi, Kerala',
    show_seller: true,
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    categories: INITIAL_CATEGORIES[6],
    sellers: INITIAL_SELLERS[1],
    product_images: [],
  },
];

export const INITIAL_ORDERS: OrderRequest[] = [
  {
    id: 'ord-1',
    reference: 'KL-2026-0001',
    customer_name: 'Rahul Varma',
    whatsapp: '9400634966',
    delivery_location: 'Thrissur, Kerala',
    instagram: '@rahulv',
    message: 'Need the RC car in red colour if available.',
    status: 'new',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    order_items: [
      {
        id: 'item-1',
        order_request_id: 'ord-1',
        product_id: 'prod-1',
        product_code: 'EK-TOY-001',
        product_name: 'Remote Control Toy Car',
        quantity: 1,
        price_at_order: 750,
      },
    ],
  },
  {
    id: 'ord-2',
    reference: 'KL-2026-0002',
    customer_name: 'Ananya Nair',
    whatsapp: '9847123456',
    delivery_location: 'Kadavanthra, Kochi',
    instagram: null,
    message: 'Please verify if the 3D nameplate can be printed in Malayalam text.',
    status: 'checking_availability',
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    order_items: [
      {
        id: 'item-2',
        order_request_id: 'ord-2',
        product_id: 'prod-8',
        product_code: 'EK-3DP-001',
        product_name: 'Custom 3D-Printed Nameplate',
        quantity: 1,
        price_at_order: 600,
      },
      {
        id: 'item-3',
        order_request_id: 'ord-2',
        product_id: 'prod-6',
        product_code: 'EK-HOME-001',
        product_name: 'Handcrafted Ceramic Coffee Mug',
        quantity: 2,
        price_at_order: 380,
      },
    ],
  },
];
